### ISSUE TITLE
可以使用os.ExpandEnv 在给定的字符串中扩展环境变量

### ISSUE THREAD

**Issue by bboysoulcn** [soxft/busuanzi#10]
这样子你的entrypoint.sh里面就不需要sed了

**Comment by bboysoulcn** [comment]
不会go，如果建议提错勿喷

**Comment by soxft** [comment]
但是目前考虑的是, config.yaml 配置文件似乎必须存在, 但是同时又引入了读取环境变量，似乎会存在一个优先级的问题, 可能会不太方便
