### ISSUE TITLE
[Feature] 建议添加一个简易的后台，实现修改访问量功能

### ISSUE THREAD

**Issue by yuantuo666** [soxft/busuanzi#13]
如果之前使用的是其他程序统计访问量，切换到使用 busuanzi 如何保留之前的数据？
虽然可以直接连接 Redis 修改，但能否添加一个简易的后台方便修改访问量。

**Comment by soxft** [comment]
期待大佬的PR

**Comment by yuantuo666** [comment]
大佬你好，已提 PR，请 Review  https://github.com/soxft/busuanzi/pull/15

**Comment by soxft** [comment]
为什么感觉修改访问量，不是很有必要，感觉有点会 “伪造” 阅读量的意思？

**Comment by yuantuo666** [comment]
例如之前使用的是 WordPress 博客，切换到使用 Hexo，使用 busuanzi 项目统计浏览量，需要修改原有访问量以保持数据一致

**Comment by soxft** [comment]
这种似乎 要改这么多访问量，也不太方便吧。不过可以考虑在 Readme 里放你的仓库链接吧
