### ISSUE TITLE
Data Backup

### ISSUE THREAD

**Issue by leimao** [soxft/busuanzi#19]
Thanks for the great contribution. I just have one quick question.
Does this app use database? (It does not seem so to me)
If the Redis service is broken somehow on the server, we will lose data, right?

**Comment by soxft** [comment]
We don't currently use any databases, and in order to optimize speed, Redis is used for data storage. The persistence of Redis ensures data consistency. But there may still be data loss. In the future, we should add scheduled data synchronization to databases such as mysql, and PR is also welcome
