### ISSUE TITLE
REDIS_PWD 在环境变量失效

### ISSUE THREAD

**Issue by pudding0503** [soxft/busuanzi#27]
我看到在 [Docker 的安装说明](https://github.com/soxft/busuanzi/wiki/install#2-%E4%BD%BF%E7%94%A8-docker-%E8%BF%90%E8%A1%8C-recommend)，其中有一个环境变量是 `REDIS_PWD `，

```yaml
environment:
   REDIS_PWD: password
```

我设置了密码，但是 redis 密码仍未空，我看到最新的 [docker-compose.yaml](https://github.com/soxft/busuanzi/blob/main/docker-compose.yaml) 文件已经移除了 `REDIS_PWD`。是未来不会再支持了吗？

**Comment by soxft** [comment]
尝试修改为 REDIS_PASSWORD, 文档忘记更新了
换成了 viper 进行配置解析，理论上 config.yaml 内的所有配置 都可以通过环境变量设置，等我稍后更新一下，感谢

**Comment by pudding0503** [comment]
非常感谢 😁
