### ISSUE TITLE
API问题

### ISSUE THREAD

**Issue by LvHrn** [soxft/busuanzi#28]
想问下GET请求不可以使用吗？我这边使用POST请求可以获取到数据，但是使用GET请求好像不能使用？

**Comment by soxft** [comment]
这个应该是在 即将发布的 2.8.3 版本内
还在修改内容

**Comment by soxft** [comment]
https://apifox.com/apidoc/shared-3915ad4e-4383-4e95-988a-fdad828dc194

对应的 API 请求 可以参考这个
