### ISSUE TITLE
GET /api won't return /dist/index.html

### ISSUE THREAD

**Issue by L1H0n9Jun** [soxft/busuanzi#30]
After migration to v2.8.3, all worked fine, except that a GET request to /api won't return /dist/index.html (as the version before v2.8), which is a kind of protection of the api.

I want to restore the behavior, would you please guide me a little bit? Thx (maybe route?).

**Comment by L1H0n9Jun** [comment]
![image](https://github.com/user-attachments/assets/579bfd08-f0f9-477b-8aa1-1024d84794be)

Works. Any side effect?

**Comment by soxft** [comment]
> ![image](https://private-user-images.githubusercontent.com/20871291/363099267-579bfd08-f0f9-477b-8aa1-1024d84794be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxOTAwNTcsIm5iZiI6MTcyNTE4OTc1NywicGF0aCI6Ii8yMDg3MTI5MS8zNjMwOTkyNjctNTc5YmZkMDgtZjBmOS00NzdiLThhYTEtMTAyNGQ4NDc5NGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDExMjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYTIxYmU5YzZlOWQ4ZDdjZjdjOTkyZmVlMDE3MjgzMjFkMDcwMGQzOWZhYTNmZDA4OTM3NjE3OGE4YjdmNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFm3wcu_EXf3B_LACvyeMx4h9qfG_7lIIkWMi6_Db5Y)
> 
> Works. Any side effect?工作。有任何副作用吗？

Sorry for the late reply.

It's okay, it doesn't have any side effects, and now the `GET /api` theoretically use fallback route here https://github.com/soxft/busuanzi/blob/a26df5b77669e5618aa22f156a2b00182569aa09/process/webutil/route.go#L28

which shows /dist/index.html
