### ISSUE TITLE
数据迁移后 访客数据异常

### ISSUE THREAD

**Issue by PearsSauce** [soxft/busuanzi#31]
我看了这篇[#25 ](https://github.com/soxft/busuanzi/issues/25#issuecomment-2082193456)  数据是迁移成功了，但访客数据异常且不会新增。地址：

<img width="370" alt="image" src="https://github.com/user-attachments/assets/bdf52d08-e427-4938-b798-5f9818a1a6e7">

我发现两份/data/bsz/config.yaml     配置项不一致，我将新的配置与旧的修改一致。
<img width="1077" alt="image" src="https://github.com/user-attachments/assets/60867311-1f2e-40f4-a134-49fa11d327a2">
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/162e9383-45e2-4892-9ef6-f73473f615c1">

通过查看redis容器数据已经是成功的迁移了过来

<img width="791" alt="image" src="https://github.com/user-attachments/assets/78c939ff-15da-456f-ba65-7ba999f97d1f">

这是博客里的获取到的数据：
<img width="585" alt="image" src="https://github.com/user-attachments/assets/24b802b5-e482-4cbd-b603-b112ff2b5a12">

请问改如何解决呢？

**Comment by soxft** [comment]
请问您的 版本是多少呢, 2.8.x 与 之前的版本 数据存储方案不一致, 不能直接迁移，P2 中为新的配置文件

如果您迁移后使用了新的版本，还应该使用 readme 中提到的 busuanzi_transfer 工具进行数据格式转换
